DOCSP-34512 update steps for Atlas Search Index Configuration File
mongodb/docs-atlas-cli pull request #231
Opened 2023-11-28 01:14 UTC by kanchana-mongodb

- [JIRA](https://jira.mongodb.org/browse/DOCSP-34512)
- [Stage](reference/json/search-index-config-file/)
- [Build](url)

2023-11-28 16:02 UTC, corryroot requested changes
Thanks @kanchana-mongodb! The spacing looks off in the new example.

2023-11-28 16:02 UTC, corryroot commented on source/includes/create-atlas-search-expanded-index-config-file.json
> +  }
Spacing looks off:
```suggestion
{
  "collectionName": "listingsAndReviews",
  "database": "sample_airbnb",
  "name": "myIndex",
  "mappings": {
    "dynamic": false,
    "fields": {
      "name": {
        "type": "string"
      },
      "property_type": {
        "type": "string"
      }
    }
  }
}
```

2023-11-28 16:02 UTC, corryroot commented on source/reference/json/search-index-config-file.txt
> +:ref:`local <atlas-deployments-search-indexes-create>` Atlas
```suggestion
:ref:`local <atlas-deployments-search-indexes-create>` |service|
```

2023-11-28 18:16 UTC, corryroot approved these changes
LGTM!

2023-12-13 19:38 UTC, tibulca approved these changes
lgtm

2023-12-15 18:50 UTC, merged