(DOCSP-36734): Add JSON configuration page for Atlas Search Nodes
mongodb/docs-atlas-cli pull request #274
Opened 2024-02-23 20:19 UTC by davidhou17

- [DOCSP-number](https://jira.mongodb.org/browse/DOCSP-36734)
- [LATEST BUILD LOG](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&amp;jobId=65d8f4217111165982b71962)

Staging:
- [JSON landing page](https://preview-mongodbdavidhou17.gatsbyjs.io/atlas-cli/DOCSP-36734/reference/json/)
- [Search Nodes Configuration File](https://preview-mongodbdavidhou17.gatsbyjs.io/atlas-cli/DOCSP-36734/reference/json/search-nodes-config-file/)
### Self-Review Checklist

- [ ] Check that the submodule pulled in the right changes (if applicable).
- [ ] [Define](https://wiki.corp.mongodb.com/display/DE/Taxonomy+tagging+instructions) taxonomy [values](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) at top of page.
- [ ] Add genre facets (tutorial or reference), as in this [example PR](https://github.com/10gen/cloud-docs/pull/5042).
- [ ] Add programmingLanguage (if necessary).
- [ ] Add meta keywords (if necessary).
- [ ] Resolve any new warnings or errors in the build.
- [ ] Proofread for spelling and grammatical errors.
- [ ] Check staging for rendering issues.
- [ ] Confirm links are working.

2024-02-25 03:34 UTC, JuliaMongo approved these changes
I also suggest that you add a link to the docs about search nodes.

2024-02-25 03:34 UTC, JuliaMongo commented on source/reference/json/search-nodes-config-file.txt
> +descriptions, refer to the :oas-atlas-op:`API specification
see the

2024-02-25 03:34 UTC, JuliaMongo commented on source/reference/json/search-nodes-config-file.txt
> +``.json`` configuration files.
Suggestion:

To create or update search nodes in a {+cluster+} you can
create a ``.json`` configuration file for search nodes and pass this file to a command with {+atlas-cli+}.

2024-02-25 03:34 UTC, JuliaMongo commented on source/reference/json/search-nodes-config-file.txt
> +     - Settings to configure search nodes for your cluster.
{+cluster+}

2024-02-25 03:34 UTC, JuliaMongo commented on source/reference/json/search-nodes-config-file.txt
> +     - Hardware specification for the search node instance sizes.
I think this setting warrants adding a link to the search nodes information where NVME is discussed. Do we have such a place in the docs? I would link to it.

2024-02-25 03:34 UTC, JuliaMongo commented on source/reference/json/search-nodes-config-file.txt
> +     - Number of search nodes in the cluster.
Use a replacement for cluster

2024-02-27 09:29 UTC, jeroenvervaeke requested changes

2024-02-27 09:29 UTC, jeroenvervaeke commented on source/reference/json/search-nodes-config-file.txt
> +    atlas clusters search nodes create --clusterName myCluster --file /search-nodes-config.json
if your file is in the same directory it should be either `./search-nodes-config.json` or `search-nodes-config.json`

2024-02-28 09:25 UTC, jeroenvervaeke approved these changes
LGTM

2024-02-28 17:23 UTC, merged